version: '3.5'

services:
  api01:
    build: ./
    hostname: api01
    depends_on:
      - db
      - redis
    expose:
      - '3000'
    deploy:
      resources:
        limits:
          cpus: '0.37'
          memory: '0.4GB'

  api02:
    build: ./
    hostname: api02
    depends_on:
      - db
      - redis
    expose:
      - '3000'
    deploy:
      resources:
        limits:
          cpus: '0.37'
          memory: '0.4GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.21'
          memory: '0.7GB'

  db:
    image: mongo:latest
    hostname: db
    environment:
      - MONGO_INITDB_DATABASE=nestjs
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    command: mongod --quiet --logpath /dev/null
    ports:
      - '27017:27017'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.75GB'

  redis:
    image: redis:latest
    hostname: redis
    ports:
      - '6379:6379'
    command: redis-server --save "" --appendonly no
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: '0.75GB'

networks:
  default:
    driver: bridge
    name: rinha
